### ISSUE TITLE
community.brave.com shows a blank page

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-ios#1067]
- Did you search for similar issues before submitting this one?
yes

- Description:
community.brave.com shows a blank page

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6s+

- Brave Version:
1.4

- Steps to reproduce:
    1. visit community.brave.com

- Actual Behavior
a blank page shows

- Expected Behavior
the proper page shows and can be interacted with

- Is this an issue with Beta build?
no

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by Jacalz** [comment]
Can not reproduce at all, has worked for since the beginning 😅

**Comment by Jacalz** [comment]
Oh never mind it doesn’t work now but it worked yesterday 😅

**Comment by Jacalz** [comment]
I don’t think this is something that regressed because it worked yesterday fo me but today it does not load just as stated above, I thought that this might be a problem with the mobil site of the community but not brave, so I tested in desktop mode but that leads me with this result instead:
[![C62459_CB-_BE72-4_D3_A-8_DD6-_C864_B6_F45194.png](https://s18.postimg.org/9v6q0abjd/C62459_CB-_BE72-4_D3_A-8_DD6-_C864_B6_F45194.png)](https://postimg.org/image/snil3v7xh/)

**Comment by Jacalz** [comment]
Sorry wrote this on the phone and hit the wrong button 😅

**Comment by jamesmudgett** [comment]
This is an issue on all iOS browsers.

**Comment by Jacalz** [comment]
This should probably be moved off the milestone 😅

**Comment by jhreis** [comment]
I'm keeping this ticket around to keep it on our radar, although I think it is completely irrelevant.

**Comment by Jacalz** [comment]
I just want to inform you all that it works in safari as of currently but not in Brave 😞

**Comment by alexwykoff** [comment]
Issue resolved via technical support w/ Discourse.
