### ISSUE TITLE
Pin code position is too high on smaller screens

### ISSUE THREAD

**Issue by Jacalz** [brave/browser-ios#1165]
# Test plan
1. Install 1.5 build on iphone 4s
2. Open set pin menu
3. Ensure its shown within frame
# 

- Did you search for similar issues before submitting this one?
Yes
- Description:
The whole pin code interface is too high on my iPhone 5s
- Device (iPhone5, iPhone6s plus, iPad 3, ?): IPhone 5s

- Brave Version:
1.4.3 17.09.12.16
- Steps to reproduce:
    1. Open settings
    2. Set a pin
    3.

- Actual Behavior
Too high up
- Expected Behavior
Should fit within the screen
- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:
[![F64766_EA-2_B76-410_F-8_CE6-_E0_A90_BA85_AEC.png](https://s26.postimg.org/7efy8yp21/F64766_EA-2_B76-410_F-8_CE6-_E0_A90_BA85_AEC.png)](https://postimg.org/image/lkvp46zx1/)
- Any related issues:

**Comment by Jacalz** [comment]
Closing this since it is fixed on latest beta build 17.09.26.16

**Comment by Jacalz** [comment]
Works like it should on latest beta (17.10.24.14)

**Comment by kjozwiak** [comment]
Thanks for verifying @Jacalz! I originally removed the `checked by qa` tag so we can add specific tags for each specific iOS but noticed it was for a 4s after the fact.

@Jacalz, just curious, are you seeing the "0" being cut off with your iPhone 4s? It might be because I'm running it in a simulator? Just wondering if you're seeing the same thing.

<img width="658" alt="screen shot 2017-10-26 at 12 18 40 am" src="https://user-images.githubusercontent.com/2602313/32034917-a900b876-b9e3-11e7-8ce0-d75b1c448f66.png">

**Comment by Jacalz** [comment]
I do not have a 4s sadly 😅

**Comment by jhreis** [comment]
I assume this is an issue. Going to re-open but bump, non-blocking.

**Comment by Jacalz** [comment]
Easiest solution is to drop iOS 9 support 😅

**Comment by kjozwiak** [comment]
Using the simulator, I double checked `iPhone 5s iOS 10.3.1` and `iPhone 5 iOS 10.3.1` and didn't see the issue as they're using a 4" display rather than the 3.5" display that the `iPhone 4` uses. So it's only affecting screens that are around 3.5".

> Easiest solution is to drop iOS 9 support

@jhreis do we have the data available that can tell us how many users are still using Brave on a iPhone 4?

**Comment by jhreis** [comment]
We are planning on dropping iOS 9 support on Brave1.6, so going to bump, and "_do not fix_" this.

**Comment by jhreis** [comment]
iOS 9 has been dropped on current development, and will be going out on this release. Closing.

**Comment by srirambv** [comment]
Verified on iPhone6 with iOS 11. Not sure if this needs to be marked as `QA/no-qa-needed` as iOS 9 support is dropped assuming 4s doesn't support iOS 11? 

cc: @jhreis
