### ISSUE TITLE
Setting browser pin overrides the manually set pin

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#1169]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Setting browser pin overrides the manually set pin
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 7+ (iOS 10.3.3)
iPad (iOS 11)
- Brave Version:
1.4.3(17.09.12.16)
- Steps to reproduce:
    1. Install beta build with browser lock option
    2. Ensure browser lock switch is kept off
    3. Manually set the pin to 1234 and confirm it
    4. Go back to settings menu and enable browser-lock switch, asks to enter and confirm pin again
    5. Enter a different pin combination
    6. Background the app and bring it back to focus
    7. Enter the pin set in step 3, doesn't unlock
    8. Enter the pin set in step 5, browser unlocks

- Actual Behavior
Setting browser pin overrides the manually set pin

- Expected Behavior
Should not ask for setting up pin again when enabling the browser-lock switch if pin is manually set

- Is this an issue with Beta build?
Yes
- Is this an issue in the currently released version?
N/A
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1. 
    2. 
    3.

- Website problems only: 
- did you check with Brave Shields down? 
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 

- Screenshot if needed:

- Any related issues:

**Comment by jamesmudgett** [comment]
Not sure I agree with behavior, would be good to confirm existing pin or perhaps be explicit user must confirm existing pin in order to enable. Worst case scenario is that we set pin (which user may have forgotten at this point) and we didn't verify with user that they remember existing pin. 

I do agree with:

1. setup new pin on first enable
2. allow user to change pin through change pin menu, require confirm existing.
3. allow pin to be turned on/off but require existing pin to make the change.
