### ISSUE TITLE
Closing tab doesn't release memory

### ISSUE THREAD

**Issue by iccub** [brave/browser-ios#1212]
- Did you search for similar issues before submitting this one?
Yes
- Description:
Memory doesn't seem to be released after closing tabs, which leads to huge memory consumption over time and app crashes.
- Device (iPhone5, iPhone6s plus, iPad 3, ?):
Tested on iP7, iPad Air 2
- Brave Version:
1.5, latest development version
- Steps to reproduce:
    1. Open XCode, run app and select 'debug navigator'(or press CMD + 7), select memory tab
    2. Open few tabs, heavy sites preferred, I tested on motorsports.com. 
    3. Close them all, one by one or all at once and notice that memory usage didn't drop by much.
    4. If you repeat 1-3 few times app will crash

This can be also done using one tab, clicking through some links, closing tab and opening new one, multiple tabs make it just faster to reproduce. After crash and tab restoration memory is not as high as before crash.

- Actual Behavior
Closing tab releases only small amount of memory.

- Expected Behavior
It should release more memory that it currently does.

- Is this an issue with Beta build?
Yes, it happens on production too.
- Is this an issue in the currently released version?
Can't debug memory on production but easily reproduced crash after load-close tabs few times.
- Can this issue be consistently reproduced?
Yes.

- Website problems only: 
- did you check with Brave Shields down? 
Yes, it's the same
- did you check in Puffin/Dolphin/iCab/Firefox (UIWebView-based browsers)? 
I tested the behavior on firefox iOS. On firefox this is also noticeable but the scale is really low. I mean, opening new tab in firefox takes few megabytes of memory, when on brave it's more like 50-150. 

For comparision, after 3 rounds of opening 15 motorsports tabs and closing them brave memory started at ~80MB and ended at ~1.2GB usage, on firefox started at ~80MB and ended at ~150MB, see screenshots below.

- Screenshot if needed:
Brave memory usage, iPhone 7
<img width="1025" alt="zrzut ekranu 2017-10-03 o 11 41 38" src="https://user-images.githubusercontent.com/6950387/31119197-71e62818-a830-11e7-842e-a0e3a7c97e17.png">

Firefox iOS memory usage, iPhone 7 simulator, couldn't build it on device, brave memory usage behaves similar on device/simulator
<img width="900" alt="zrzut ekranu 2017-10-03 o 11 45 34" src="https://user-images.githubusercontent.com/6950387/31119263-a20cd2a8-a830-11e7-821e-827202149958.png">

- Any related issues:

**Comment by SlayterDev** [comment]
I've been digging in to this issue a bit as referenced in PR #1218. I just wanted to share a little of what I've found so far. It's obvious that when the tabs are being closed that the `Browser` is being retained rather than releasing like it should. I dug through all the places where a reference to the `Browser` was being store to ensure there were no strong reference cycles. It looked like every place was holding a `weak` reference _except_ in the `TabBarCell`. Changing its reference to the `Browser` to `weak` has already dramatically improved memory usage as can be seen here:

![Memory Graph](https://user-images.githubusercontent.com/1760134/31205412-e0d0e98c-a936-11e7-918a-d27602b8ce37.png)

As you can see in the graph it looks like there are still some objects being held in memory (we still have more memory in use after all tabs are closed than before they were opened) so I will continue looking in to this but I believe this is a step in the right direction.

**Comment by iccub** [comment]
Improvement looks nice, great find. I also looked for lack of `Browser` weak references, must have missed this one apparently.

Compared to firefox iOS codebase, I was suspicious about [TabsList](https://github.com/brave/browser-ios/blob/0859c2ed204e674c8091686e5adc945e47da01da/Client/Frontend/Browser/TabManager.swift#L63), a lot of `Browser` references sitting there, but tinkering around this class didn't do trick for me.

Good job anyway, Brave devs should like it.
