### ISSUE TITLE
Shopping Info Blocked on Disneystore.com

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-ios#127]
http://www.disneystore.com/toy-story-tee-for-boys/mp/1383104/1000228/

When looking at a clothing item, with the ad blocking on, the "add cart, select size/quantity" buttons are blocked.  When disabling, they are there.  This does not happen in the OSX version.
![image](https://cloud.githubusercontent.com/assets/16989308/12981513/f43c5478-d0ae-11e5-8ec4-18e5b3897d6c.png)
![image](https://cloud.githubusercontent.com/assets/16989308/12981514/f4480980-d0ae-11e5-961b-c6fd419d07d2.png)

**Comment by garvankeeley** [comment]
This is really quite serious. I have to change the logic on my http filter class.
The http filter (i.e. UrlProtocol class) has 2 calls at the start from the system, the first is
1) does your class handle this request, I say yes to this 
2) what is the canonicalURL for this request, in here I can Adblock, TP, and HTTPSE filter and return an empty url or a new url. Or, i return the URL passed in, which is the normal/default behaviour.

In this case, the Adblock, TP, and HTTPSE have nothing to do with the bug. When shield button is off, the easiest bypass is at step1. So the UrlProtocol doesn't get used.
The fix is to add the AB/TP/HTTPSE checks at step 1, and if the url isn't going to handled any further, return false.

There is clearly more research needed here, but if I change the logic, this site loads ok.
