### ISSUE TITLE
Bookmark sync for Iphone

### ISSUE THREAD

**Issue by artella-coding** [brave/browser-ios#1570]
Will bookmark sync ever become available for the Iphone? Currently can add bookmarks on the iphone but there is no sync facility which would allow me to access those bookmarks from the desktop.

**Comment by iccub** [comment]
Yes, we are working hard to make that happen. Sync will be available on all platforms. 
We have already started beta testing sync, you need to wait some more time until it's finished.

Synchronization is a complex problem overall and in addition to that, our sync implementation is going to be encrypted, that's why it takes us long time to make it work.

You can track our progress on sync for iOS here https://github.com/brave/browser-ios/issues?utf8=✓&q=label%3Afeature%2Fsync+, all sync tasks are labelled.

I will close this ticket but feel free to comment if you have any other issues.

**Comment by artella-coding** [comment]
Thank you that is excellent.

**Comment by artella-coding** [comment]
@iccub New article on bookmarks syncing came out from the Firefox team yesterday [Deep Dive: New bookmark sync in Nightly](https://blog.nightly.mozilla.org/2018/05/14/deep-dive-new-bookmark-sync-in-nightly/). Thought it might be of interest to you.
