### ISSUE TITLE
3d touch privacy consideration

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#164]
Posted for a friend: 

The 3D touch displays the last website that has been bookmarked via "Open Last Bookmark". I'm not sure this is a great idea as it might be leaking some information.. I personally don't feel comfortable having Brave list the last bookmark that I've added. The other issue is that even if you do remove the bookmark, it will still appear as the last one that was created.. Attached issue1.PNG to demonstrate the issue.
![issue1](https://cloud.githubusercontent.com/assets/831718/13578085/d2d3df86-e463-11e5-981c-1ec58e8e4947.PNG)

**Comment by garvankeeley** [comment]
All the 3D touch features we inherited from Firefox iOS, I am tempted to disable them as they are a fringe feature for us that isn't well tested (or reviewed by us specifically to see how well they fit into the product).
I tend to trust that fx team has reviewed the priv implications of features such as this, but because of our specific market for Brave, we might have to be extra cautious with privacy issues.
 I am ok to remove this, cc @bradleyrichter for added comment

**Comment by bradleyrichter** [comment]
@garvankeeley sure. either disable it completely or remove the bookmark item.
