### ISSUE TITLE
Context menu bug on skysports (shows only Cancel)

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#172]
From a freind:
STR: (attached contextMenuIssue.PNG)
- visit http://www.skysports.com
- tap on any article that's related to football (soccer)
- scroll to the bottom of the article and you should see a list of "Trending" articles
- tap and hold any of those articles 
- Rather than getting a context menu with several options, you'll only see "Cancel"

**Comment by bbondy** [comment]
![contextmenuissue](https://cloud.githubusercontent.com/assets/831718/13927463/2f093f3a-ef68-11e5-9940-5ff8f0dd3d1b.PNG)

**Comment by garvankeeley** [comment]
Thanks, will check it out. 

For the curious reader: the context menu code is insane because we have to battle the UIWebView showing its own context menu; the worst-case behaviour will be when that happens, which may happen on iframes. That aside, it will be interesting to see what case this is, it looks like it is still hitting our context menu code (not built-in), which is a relief.

**Comment by garvankeeley** [comment]
see also #191
