### ISSUE TITLE
Concealing tabs on separate page is poor UX

### ISSUE THREAD

**Issue by SeAlgoAsoma** [brave/browser-ios#198]
Trying to close a tab or select a different tab under the current scheme is a pain. Either should be possible with a single tab. Instead it's:
1.) Hit numeric tabs indicator to open "Tabs" page
2,) Use finger to scroll through many open tabs (I typically have many open) which all look identical because most don't load preview thumbnails
3.) Optional: close current tab by tapping X, then search for tab you want to move to
4.) Select tab you want to move to

Why so many gestures required? Just put the tabs across the top of the window like every other browser does it, with little close buttons on each tab. Easy peasy.

At least respect a cmd-w from an attached bluetooth keyboard to close the currently open tab. 

Having to flip to a different view to do any tabbed navigation is just not a smooth experience.

**Comment by garvankeeley** [comment]
Is this on iPad or iPhone?

**Comment by bradleyrichter** [comment]
sounds like iPad and I agree 100%. iPad needs tabs ASAP.

**Comment by Calefornia** [comment]
With the current layout, it can be tough to see which tab I'm using from within the grid of tab tiles. With some highlighting, it would be much more clear. It's possible to lose track, especially when titles can't be read. A faint glow or something could help with this. I like that the tiles are put on top of the current tab instead of opening a new viewing context, but perhaps some better management could help with many tabs as noted above. In my opinion, there is nothing wrong with the tab system aside from the lack of indication on which tab is being viewed from the grid. If this isn't clear, I can edit this post with a screenshot later. Thanks

**Comment by SeAlgoAsoma** [comment]
Hi, sorry, didn't see the previous replies to this. It's iPad. I didn't realize Brave is built on iOS Firefox, from which this UI originates. I've tried to keep using it, but this way of doing things is very annoying, I feel like I never know "where" I am, and the navigation just feels so cumbersome, with having to go through this many actions to close or change tabs. The idea that to just close a tab you have to leave it, then immediately locate it and come back to it via a different interface, is absurd. I can't understand why they went with this design.

**Comment by bradleyrichter** [comment]
@SeAlgoAsoma Have you tried the latest version on iPad with normal tabs now?

We will still make improvements to the previews in portrait phone view but those will be separate git issues so I will close this one.
