### ISSUE TITLE
App is crashing when moved to background

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#212]
```
#14
Crashed: com.apple.root.default-qos
EXC_BREAKPOINT 0x00000001006938ac
 Raw
0	Storage	
SQLiteBookmarksModel.swift line 0
specialized thunk
1	Shared	
DeferredUtils.swift line 154
(chainDeferred<A, B> (Deferred<Maybe<A>>, f : (A) -> Deferred<Maybe<B>>) -> Deferred<Maybe<B>>).(closure #1)
2	Deferred	
Deferred.swift line 94
_TFFC8Deferred8Deferred9bindQueueurFTPSo17OS_dispatch_queue_1fFxGS0_qd____GS0_qd___U_FQd__T_
3	Deferred	
Deferred.swift line 68
_TPA__TFFC8Deferred8Deferred9uponQueueFTPSo17OS_dispatch_queue_5blockFxT__T_U0_FT_T_

```

Due to DB shutdown on other thread

```
8	Storage	
SwiftData.swift line 582
ConcreteSQLiteDBConnection.deinit.(closure #1)
11	Storage	
SwiftData.swift line 507
ConcreteSQLiteDBConnection.__deallocating_deinit
12	Client	
Profile.swift line 243
BrowserProfile.shutdown() -> ()
13	Client	
AppDelegate.swift line 338
specialized AppDelegate.(applicationDidEnterBackground(UIApplication) -> ()).(closure #2)
```

**Comment by garvankeeley** [comment]
@bradleyrichter and @jhugman this is what you were seeing I suspect.

**Comment by garvankeeley** [comment]
This has some insight into why the shutdown takes place on backgrounding: https://bugzilla.mozilla.org/show_bug.cgi?id=1224692

@rnewman do you recall if there is specific handling for db shutdown while another thread is accessing? It should be safe as SwiftData.sharedConnection is referenced by other operations. 
I'll investigate more next week

**Comment by rnewman** [comment]
The `EXC_BREAKPOINT` you're seeing here is an implicitly unwrapped optional, which reminds me of Bug 1236956.

More context:

We shutdown on background if we're not working because once backgrounded we could then be killed at any time with no further warning, and so it's best to be ready. The system SQLite should make sure being killed is safe, but that's not a nice bet to make.

We jump through a few hoops to make sure we don't ever close the connection while work is underway, including syncing on exit: I think Bug 1168504 covers most of them.

`SwiftData` serializes operations, so you shouldn't ever have truly concurrent access if you're following the same approach we do.

**Comment by mrose17** [comment]
@garvankeeley - i take it that there's no way to test it without a crash? or should sqlite ops not be invoked when in the background? or ...

**Comment by garvankeeley** [comment]
There is no reason the existing code should crash, all SwiftData db ops are serialized, and the existing shutdown of the db code just dereferences the global handle to the db.
Any code change here will be research oriented to see if crash incidence can be reduced by changing the approach slightly.

**Comment by garvankeeley** [comment]
Closing, no longer happening, been watching for weeks for any reports.
