### ISSUE TITLE
Brave crashing on startup (required reinstall)

### ISSUE THREAD

**Issue by bbondy** [brave/browser-ios#260]
Posting for a friend:
I'm not 100% sure how to reproduce this, but I got Brave into a state where it was crashing as soon as the onboarding screen was loading. I couldn't recover from this state and had to re-install the update which fixed the problem. Here's the use case I was going through when this happened:
I had Brave running in the background with about 10 websites/articles opened that I still wanted to read
Switched into Brave and got the modal window indicating that there's an update available: v1.2.6 (16.06.13.09)

Once the update was installed, Brave relaunched with the onboarding screen in front which at that point, Brave started crashing instantly.

Video of the issue: https://youtu.be/dGe1xgKPz5Q

**Comment by bbondy** [comment]
@garvankeeley maybe you can find on crashlytics?

**Comment by garvankeeley** [comment]
During the beta cycle I missed a DB migration while iterating through some DB changes, so BraveBeta can crash on startup. I had put in the beta release notes that going to Settings>Clear Private Data would reset the DB, but I didn't expect this crash so early in startup so that you can't get to that screen.
BraveBeta must be deleted as the db is now corrupt.

**Comment by garvankeeley** [comment]
I don't see any crashes for this. Crashlytics should catch any crash that happens after the splash screen, and anything earlier I check Apple's crash reporting for. 
Apple's crash reporting requires that the device be plugging in to sync (not wifi sync AFAIK), and reports are often a week or more delayed.
