### ISSUE TITLE
improve ensureMainThread function

### ISSUE THREAD

**Issue by diegodoval** [brave/browser-ios#321]
Currently in BraveUtil we've got

```
func ensureMainThread(closure:()->()) {
    if NSThread.isMainThread() {
        closure()
    } else {
        dispatch_async(dispatch_get_main_queue(), closure)
    }
}
```

we should change it to 
```
func ensureMainThread(closure:()->()) {
    if NSThread.isMainThread() {
        closure()
    } else {
        dispatch_sync(dispatch_get_main_queue(), closure)
    }
}
```

so that the dispatch line maintains synchronicity which is what's expected from "ensureMain" -- and what the first part of the if() does if we're already on the main thread.

**Comment by garvankeeley** [comment]
And a comment that this is a marker for areas of the code where we aren't sure of the thread state, or just being extra-defensive. (for instance UIWebView, networking entry points, extensions, etc. are all off-main, but the codebase is large enough it isn't always clear if code is hit from these entry points). 
I'll look at all my use/abuse of this function and just change to delay(0) -> the related handy function to post async to main.
Should we rename delay() to postAsyncToMain()? I fear it isn't named clearly enough.

**Comment by garvankeeley** [comment]
Removed by https://github.com/brave/browser-ios/commit/907b4c3180102e0eaf5da13b99a389efe1d11f47

It was a band-aid during porting from Firefox iOS. Entry points and thus thread states were different between our app and Firefox iOS, and due to size/complexity of app, extra guards were in place. We now have our entry points wrapped to post events to main thread. Code that is expected to handle being off-main will call postAsyncToMain().

**Comment by garvankeeley** [comment]
See also previous commit, which renamed and added comments to usage of postAsyncToMain():
https://github.com/brave/browser-ios/commit/54865ea8fca480ce2265baf6912c39d6f5717128
