### ISSUE TITLE
Tapping links, progress bar not always showing, thus no visual feedback of having tapped (STR?)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-ios#350]
From support:

> When I click on a link there is no progress bar to inform me if I have hit the link or if the link has registered and the page is loading. I find myself tapping Links repeatedly because I'm unsure if it registered.

**Comment by garvankeeley** [comment]
Agreed, very annoying. Long standing bug, very difficult to fix. We need to find out what type of links trigger this, and handle each case. The web view had different notification systems for different navigation methods (i.e. a href link, vs JS nav methods). History push state nav is almost guaranteed to cause this because the webview component lacks notifications.
