### ISSUE TITLE
Certain BM urls won't move to a folder

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#639]
Report that certain sites aren't moveable to BM folder:
https://www.entrepreneur.com/article/286964 

I verified this is in fact the case with this URL.

**Comment by jhreis** [comment]
This seems to be caused by the related title containing an apostrophe (`'`), reproducible, elsewhere:
https://www.yahoo.com/tech/lenovo-smart-assistant-amazon-alexa-230217198.html

There is an db error log printed out when an issue arrises:
> err = Error Domain=org.mozilla Code=1 "SQL error or missing database near "s": syntax error" UserInfo={NSLocalizedDescription=SQL error or missing database near "s": syntax error}

In this case the `s` being the character following the apostrophe

Does seem to work fine with curved apostrophes:
https://techcrunch.com/2017/01/04/live-from-samsungs-2017-ces-press-conference/

**Comment by srirambv** [comment]
QA Steps: 

1. Bookmark the below sites
https://techcrunch.com/2017/01/04/live-from-samsungs-2017-ces-press-conference/
https://www.yahoo.com/tech/lenovo-smart-assistant-amazon-alexa-230217198.html
https://www.entrepreneur.com/article/286964

2. Create a bookmark folder
3. Should be able to move the bookmarks into the folder
