### ISSUE TITLE
 technobuffalo.com iPad/iphone ads getting through that aren't in Android, and faster load time with shields down

### ISSUE THREAD

**Issue by garvankeeley** [brave/browser-ios#647]
I can't see them @lukemulks, can you give me specifics or screenshot what you are seeing?
<img width="303" alt="screenshot 2017-01-09 17 18 00" src="https://cloud.githubusercontent.com/assets/5495083/21786043/1daeab3e-d690-11e6-87a4-f022a8942ca2.png">

**Comment by lukemulks** [comment]
During benchmarking, it was observed that while iOS had shields up, there were several domains tested that appeared to be blocking some, but not all ads and tracking. 

There was one instance with bradsdeals.com where we observed what appears to be an anti-ad blocker, which we can investigate further (noted in the txt doc). 

Observations were made from myself and Alex during testing. Alex was using an iPhone 6 (OSv9.3.5), I was using an iPad 2 (OSv9.2.1). Both of us were using the latest market-available release: v1.2.19. 

To determine which ad and tracking domains had gotten beyond the Shield Up blocking settings, I compared the Shield Up and Shield Down Android session captures against the iPad and iPhone Shield Up session captures, and pulled all ad and tracking events that were called with Shields UP for the iPhone and iPad for each domain in the attached text doc. 

If your team could review the domains listed in the events from the attached txt doc, and see if your devices are also allowing these domains to get beyond the shield blocking, it may point to a bug in how the blocking filtering is working in iOS. 

Some of these domains, such as Bluekai, Rubicon, Taboola and others listed are definitely on both the easylist and disconnect.me blocklists. 

Some of the traffic captured appears similar to what I've captured in Chrome with the Easylist Exceptions list when Acceptable Ads are allowed in AdBlock Plus. It might be worth checking to see if that list is being used in iOS, instead of the Easylist blocklist. 

I have session captures and any additional info that I'm happy to provide from the benchmark testing. 

Note: The Bradsdeals domain items will be investigated outside of this issue, no need to pursue or investigate those items on this ticket. 

Thanks, 
Luke

[Brave Benchmarking-ios-blocking-notes-01.09.2017.txt](https://github.com/brave/browser-ios/files/695129/Brave.Benchmarking-ios-blocking-notes-01.09.2017.txt)

**Comment by garvankeeley** [comment]
I am trying to understand a subset that I can debug, for instance I see:
```
domain: technobuffalo.com | IPAD - shields up
BLOCKED IN ANDROID - NOT BLOCKED IN IOS
https://www.googletagservices.com/tag/js/gpt.js
https://www.google-analytics.com/ga.js
https://www.google-analytics.com/r/__utm.gif?
```
@bbondy I thought google domains like this were not supposed to be blocked?

**Comment by garvankeeley** [comment]
We can unit test (outside of the webview context) sets of domains/URLs on iOS if there is a specific dataset we should do that with.
The first question is "are the expected domains/URLs being blocked in the unit test.?"
Then if they are, but not block during webview loading, then we have to see what is happening in there. For instance, are the parent domain of those requests being set to the domain of the main page, that would be a tricky problem to fix as that info comes from Apple APIs.

**Comment by lukemulks** [comment]
The "blocked in Android, not blocked in iOS" calls for each domain are
blocked in Android as expected, and fall under the ad block and tracking
protection blocklists, but are for some reason not being blocked with
shields up in iOS.

The issue is that the URLs for the listed events in the attached doc were
being called (domains for the URLs should have been blocked by the client
and not shown up in the network traffic), as opposed to a CSS or other
blocking method at the DOM level in WebView.

So I basically am requesting to see if anyone is able to run a shields up
check with ad blocking settings selected for the few domains that are
listed (KTLA.com, TMZ.com, technobuffalo.com) to see if you're able to also
see the events listed for those domains called when observing network
traffic.

We definitely should be seeing the calls blocked that were listed as
"blocked in Android, not blocked in iOS".

From what I have observed, I suspect that there may be an issue with the
blocklists that are live, specifically with iOS, but only have traffic
captures from two iOS devices so far.

I'm not sure where to check to see which blocklist versions are currently
active specifically in the iOS market release, otherwise I could have
checked to confirm in advance.

*@bbondy*, is there any chance the latest updates that were made to the
Brave blocklist hosting (migrated under brave org) may be resulting in what
we're seeing in iOS since that update took place inbetween iOS market
release updates? Maybe they haven't cutover yet, or would they still be
linked to the previous locations?



On Jan 9, 2017 6:55 PM, "Garvan Keeley" <notifications@github.com> wrote:

We can unit test (outside of the webview context) sets of domains/URLs on
iOS if there is a specific dataset we should do that with.
The first question is "are the expected domains/URLs being blocked in the
unit test.?"
Then if they are, but not block during webview loading, then we have to see
what is happening in there. For instance, are the parent domain of those
requests being set to the domain of the main page, that would be a tricky
problem to fix as that info comes from Apple APIs.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/brave/browser-ios/issues/647#issuecomment-271472935>,
or mute the thread

**Comment by garvankeeley** [comment]
@alexwykoff @lukemulks 
There is a way to check if an url should be blocked using ad-block tools:
`node scripts/check.js --host www.cnet.com --location https://assets.bounceexchange.com/assets/uploads/clients/1362/ads/c33ddf103c79bec5be2e539c96bec6d3.png `
Matches: False

Please file any issues against ad-block repo. If there is a discrepancy between ad-block and iOS, then we can file here. On iOS the ad-block lib is used as-is. 
Website assets are different between platforms and form factors, so there will be differences in sets of URLs between Android/iOS and screen sizes.

**Comment by garvankeeley** [comment]
Exact info is here: https://github.com/brave/ad-block#util-for-checking-urls

**Comment by garvankeeley** [comment]
Closing, please re-file if you want me to look at a case for Shields Up being faster. 
Website asset loading is chained on certain sites so that a particular asset is required to load before another, or an alternate loading can happen if a required/expected asset doesn't load.

**Comment by lukemulks** [comment]
Thanks Garvan, appreciate the info.

Will investigate, and follow up as advised.

**Comment by garvankeeley** [comment]
I found the problem! HTTPSE is the problem, the HTTPSE check for upgrade is before the check for blocking. It *should* be checked again after upgrade, but for some reason it isn't. Reopening the bug.

**Comment by garvankeeley** [comment]
@bbondy found it ^^^

**Comment by lukemulks** [comment]
This is fantastic news. Thanks for the update!

**Comment by bbondy** [comment]
btw a friend of mine was reporting several ads being shown so I think the problem might be more frequent than we think.  I asked him to check back after the next release.

**Comment by lukemulks** [comment]
Thanks

If your friend recalls which domains were leaking the ads, I would be happy
to add them to the list to check as well.
