### ISSUE TITLE
Tab preview is not shown until the specific tab is opened

### ISSUE THREAD

**Issue by srirambv** [brave/browser-ios#699]
Description:
Tab preview is not shown until the specific tab is opened

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should show the tab preview in tab tray if the page is completely loaded

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
iPhone 6 (iOS 10)

- Brave Version:
1.2.0 & 1.3.0 (existing behavior)

- Steps to reproduce:
    1. Open a tab and tap on the top site tile to launch the page
    2. While the page is loading tap on new tab button and open a different top site
    3. Repeat the steps for all the top site tiles
    4. Tap on the tab overview, only the page favicon is shown and the tab is blank
    5. Tap on any of the tab which is blank, page is completely loaded but the preview is not shown
    6. After the tab is focused, if you view tab overview the preview is shown for the tab opened in step 5

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:

- Any related issues:

**Comment by LaurenWags** [comment]
When I follow steps 1-4, this is what I see:
![img_4825](https://user-images.githubusercontent.com/28145373/31616151-e33d7a2e-b259-11e7-9346-f9eff9f6c682.PNG)

Then, after following steps 5&6, i see this: 
![img_4826](https://user-images.githubusercontent.com/28145373/31616182-f90b9aa2-b259-11e7-85a7-e469d593a315.PNG)

**Comment by jamesmudgett** [comment]
The new behavior is intentional, here's why:
 
Tabs are no longer restored fully on app launch. In previous versions new web views were loaded and each site was loaded into memory in order to capture the screenshot. This isn't the case anymore. Instead, we launch dormant tabs and screenshot are restored from a new image caching system. If the image cache is missing we fall back to the enlarged favicon you see there.
